# application.properties
spring.main.banner-mode=off
logging.level.org.springframework=WARN

# Configuration du répertoire des chansons (changer selon vos besoins)
playlist.directory=d:/IT.University/S6/Mr_Naina/playlist/playlist-generator/songs

# Configuration du fichier de log
playlist.log.file=d:/IT.University/S6/Mr_Naina/playlist/playlist-generator/playlist.log

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/playlist_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
